# Header
menu:
  个人主页: https://www.stdioa.com/
  博客主页: /
  所有文章: /archives
  关于我: /about
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: https://github.com/StdioA
  # weibo: http://weibo.com/stdionoi/
  # zhihu: http://www.zhihu.com/people/stdioa
  telegram: https://telegram.me/StdioA
  mail: mailto:stdio_dai@nuaa.edu.cn
  rss: "/atom.xml"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

# rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: UA-65107715-1
favicon: /favicon.ico

cnzz_analytics: 1258492651

#你的头像url
avatar: /pics/avatar.jpg
#是否开启分享
share_jia: false
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
# duoshuo: stdioa
duoshuo: false

#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  我的乐谱分享站: http://sheet.stdioa.com/
  Rexskz: https://rexskz.info/
#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 集死宅和现充于一身的小孩子。
