# Header
menu:
  主页: /
  所有文章: /archives
  关于我: /about
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: https://github.com/StdioA
  weibo: http://weibo.com/stdionoi/
  # zhihu: http://www.zhihu.com/people/stdioa
  telegram: https://telegram.me/StdioA
  mail: mailto:stdio_dai@nuaa.edu.cn
  # rss: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

# rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: UA-65107715-1
favicon: /favicon.ico

#你的头像url
avatar: /avatar.jpg
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: false
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  Rexskz: http://rexskz.sinaapp.com/
#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 集死宅和现充于一身的小孩子。
